### PR TITLE
add minimize button

### PR DESCRIPTION
**Pull request by binki**
Unfortunately the minimize button causes part of the title bar to be covered.

### CODE REVIEW

**Comment by joelpurra** [comment]
@binki: thanks for the pull request! As the window behavior of the X-Mouse Controls window in particular is crucial to the operation of the program, I am reluctant to accept the pull request without testing it myself. Unfortunately other programming work is getting in the way of setting up the right development environment to test it, which is why I'll have to let it rest for now. Thanks again, and sorry about not getting to yet =(

**Comment by joelpurra** [comment]
@binki: quick reply. Work keeps me busy. While I did get to setting up a new virtual machine for some "pure" system testing, I didn't get to testing this pull request yet. Sorry about that. No need to lose hope though =)

**Comment by binki** [comment]
@joelpurra No problem. Also, no need to use this PR when you do find time to look at #5. This PR is quite trivial and I haven’t made any attempt to make things “look good” after just setting the minimize button to display ;-).

**Comment by joelpurra** [comment]
@binki: merged, many thanks =)

**Pull request merged**
